# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rfabric < Formula
  desc "CLI for the rFabric robotics lifecycle platform"
  homepage "https://rfabric.io"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfabric/cli/releases/download/v0.0.1/rfabric_0.0.1_darwin_amd64.tar.gz"
      sha256 "35d2877d96d4fd43deaef79eb4c904b86d7d62ec24967453452ce19e42ba4a63"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfabric/cli/releases/download/v0.0.1/rfabric_0.0.1_darwin_arm64.tar.gz"
      sha256 "b76737280145802a1fae4ece49efe7dbb3ff2f820b773eca8fea809898c7a798"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.1/rfabric_0.0.1_linux_amd64.tar.gz"
      sha256 "5389ceb7500c5dabbab327e60612b494a5d8a0121e6d458de0102e1645e03be2"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.1/rfabric_0.0.1_linux_arm64.tar.gz"
      sha256 "a0d4d0e2a9e72b0322f181e0dd1d1b21ce7c4656395893d2544aa14645b6c915"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  test do
    system "#{bin}/rfabric", "version"
  end
end
