# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rfabric < Formula
  desc "CLI for the rFabric robotics lifecycle platform"
  homepage "https://rfabric.io"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfabric/cli/releases/download/v0.0.4/rfabric_0.0.4_darwin_amd64.tar.gz"
      sha256 "742d6ed28bbbe236ff649807e04ad0121e8f6c3df1164f557f6d274381338901"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfabric/cli/releases/download/v0.0.4/rfabric_0.0.4_darwin_arm64.tar.gz"
      sha256 "2b615aeb01adeb6835ff610f8dd5242ade5ede1d55779ea60e097e39edcdc21d"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.4/rfabric_0.0.4_linux_amd64.tar.gz"
      sha256 "f074322fa9153a8d6f3e924b567b4843a283dca6c9d144b5a96b3a036fa9344b"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.4/rfabric_0.0.4_linux_arm64.tar.gz"
      sha256 "b8128bcb130100d1a8917247fff830fee719498ac5f9c997638791c2b075f3bc"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  test do
    system "#{bin}/rfabric", "version"
  end
end
