# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rfabric < Formula
  desc "CLI for the rFabric robotics lifecycle platform"
  homepage "https://rfabric.io"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfabric/cli/releases/download/v0.0.5/rfabric_0.0.5_darwin_amd64.tar.gz"
      sha256 "50cc79ef5aa446afcea366e8964a2cbf7fbe2cf950a9c47b7be9b773baf932ca"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfabric/cli/releases/download/v0.0.5/rfabric_0.0.5_darwin_arm64.tar.gz"
      sha256 "be8cf83fa9992f5d4eb013c2677ee245cd0add273c1df819d8ae2fad3b669a6a"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.5/rfabric_0.0.5_linux_amd64.tar.gz"
      sha256 "798145f920b2c6ab341aac2785b23a95f44fcb519fe1a58878f83cc7bbed225b"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.5/rfabric_0.0.5_linux_arm64.tar.gz"
      sha256 "ca568b17aea6b516a385dadb0cebccf700a4c29bb5933b9ff33d69a334e3c8e5"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  test do
    system "#{bin}/rfabric", "version"
  end
end
