# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rfabric < Formula
  desc "CLI for the rFabric robotics lifecycle platform"
  homepage "https://rfabric.io"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfabric/cli/releases/download/v0.0.6/rfabric_0.0.6_darwin_amd64.tar.gz"
      sha256 "a21f42efd23a7bacad6e898d5789262c93a7e832c5aa791e73b1707d603ba1ed"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfabric/cli/releases/download/v0.0.6/rfabric_0.0.6_darwin_arm64.tar.gz"
      sha256 "f532ea221b2a690340aa477074b3d8c22fc1dfcbeccfa7280dcba7ad5a616272"

      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.6/rfabric_0.0.6_linux_amd64.tar.gz"
      sha256 "e090ee87dfdaca60c52700d09063706af3e6e6d4267fc52f57e6ae3523b0eaed"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.0.6/rfabric_0.0.6_linux_arm64.tar.gz"
      sha256 "40b5ffd0f2b4bb3b1a22bd247ce91f5fd077881d5edb504febcb6e0b327bb9a3"
      define_method(:install) do
        bin.install "rfabric"
      end
    end
  end

  test do
    system "#{bin}/rfabric", "version"
  end
end
