# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rfabric < Formula
  desc "CLI for the rFabric robotics lifecycle platform"
  homepage "https://rfabric.io"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfabric/cli/releases/download/v0.1.0/rfabric_0.1.0_darwin_amd64.tar.gz"
      sha256 "cdab452e727d5fe4d12fff2155de21788dfccb222a4fceeb633ac24420279b6f"

      define_method(:install) do
        bin.install "rfabric"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfabric/cli/releases/download/v0.1.0/rfabric_0.1.0_darwin_arm64.tar.gz"
      sha256 "f9c0d66df895cc288c45eec9e879df73c19216d9f9e5eb8fac5e0a95ddec9499"

      define_method(:install) do
        bin.install "rfabric"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.1.0/rfabric_0.1.0_linux_amd64.tar.gz"
      sha256 "d82766d975622bb61570ccca392f37649c508b9a2a441b9ba2498c6f7f53624a"
      define_method(:install) do
        bin.install "rfabric"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfabric/cli/releases/download/v0.1.0/rfabric_0.1.0_linux_arm64.tar.gz"
      sha256 "5ee48060cc656123dadb0a997fb0ee0768d763851fcc93b1e3c7295e1152f5c3"
      define_method(:install) do
        bin.install "rfabric"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/rfabric", "version"
  end
end
